### PR TITLE
Try to implement the configuration tool of chewing using Tornado-based web service.

### PR DESCRIPTION
**Pull request by PCMan**
Replace Active X use in javascript with ajax calls to a local Tornado-based web api server.
Later, we can implement user phrase editing based on this python server.
Known issues:
1. Access control: we need to avoid connecting to other users's local servers on the same machine. Some API key or simple authorization might be needed.
2. Reuse existing web server instance if there is any instead of creating a new one everytime.
3. Encapsulate the web config server in a class for reuse by other input modules.

### CODE REVIEW

**Comment by PCMan** [comment]
@timtan @lyenliang @jessy1092 Since this is quite a huge change, your review is really wanted.
I'm not good at python web programming so there are still some security issues in the web server part. :-(
With this change, we can do anything in the configuration tool later, not only simple file I/O.

**Comment by PCMan** [comment]
I plan to implement a user phrase editor for chewing based on this local web server.

**Comment by jessy1092** [comment]
@PCMan   WoW. I will review on this weekend as I can.

**Comment by jessy1092** [comment]
Maybe remove `Tornado`'s `test` folder? I think it don't need to run `Tornado` test.

**Comment by PCMan** [comment]
I already finish fixing all of the known bugs in this branch.
If no obvious problems are found, I'm going to move this to master branch.
With the new architecture, we don't need to use ActiveX objects in JavaScript.
Also, we can do much more things in the config tool since we have a full python environment for it.

**Comment by timtan** [comment]
due to there are too much tornado code.  can we list file exclude tronado?

**Comment by PCMan** [comment]
@timtan:
in server/input_methods/chewing:
    chewing_ime.py
    config/configTool.py
    config/js/config.js
Thanks!

**Comment by timtan** [comment]
感覺滿快就寫一版功能完整的 tornado  server 了。   timeout_handler,  auth_token  這幾個 handler, 是不是可以傳進 KeepAliveHandler 的建構子內? 這樣就可以不用 global 了。

**Comment by PCMan** [comment]
Merged. Will do some more refactor later.

**Pull request closed without merging**
