### PR TITLE
onActivate function裡設定下方的FIXME command刪除

### PR DESCRIPTION
**Pull request by henry10039980**
之前有在https://github.com/EasyIME/PIME/issues/94 
提到發現這個功能已經實做,因為我一開始看到這行註解也在研究看是哪邊沒改好,不過好像功能在以下的commit:https://github.com/EasyIME/PIME/commit/0ee76e2e978006112a6eb8807091da3cb9549977 已實做出來
所以幫忙把註解刪掉,若有人想幫忙貢獻可以趕快從其他方面著手~

### CODE REVIEW

**Comment by jserv** [comment]
You should explain in GIT commit messages as well.

**Comment by henry10039980** [comment]
謝謝提醒!已經更改了裡面的GIT commit messages 並加上解釋~

**Comment by jserv** [comment]
@henry10039980 : You should mention which commit implemented what you would like to manipulate with.

**Comment by henry10039980** [comment]
謝謝您的提醒!已經做了一些修正並在GIT commit messages裡新增在commit:https://github.com/EasyIME/PIME/commit/0ee76e2e978006112a6eb8807091da3cb9549977已完成popup menu的功能~

**Pull request merged**
